import { Schema, ColType, Modifier } from '@/lib/types/schema'

type SQLDialect = 'postgresql' | 'mysql' | 'sqlite'

function mapTypeToSQL(type: ColType, dialect: SQLDialect): string {
  const map: Record<ColType, Record<SQLDialect, string>> = {
    int: { postgresql: 'INTEGER', mysql: 'INT', sqlite: 'INTEGER' },
    text: { postgresql: 'TEXT', mysql: 'VARCHAR(255)', sqlite: 'TEXT' },
    float: { postgresql: 'NUMERIC(10,2)', mysql: 'DECIMAL(10,2)', sqlite: 'REAL' },
    date: { postgresql: 'DATE', mysql: 'DATE', sqlite: 'TEXT' },
    datetime: { postgresql: 'TIMESTAMP', mysql: 'DATETIME', sqlite: 'TEXT' },
    bool: { postgresql: 'BOOLEAN', mysql: 'TINYINT(1)', sqlite: 'INTEGER' },
    image: { postgresql: 'TEXT', mysql: 'VARCHAR(512)', sqlite: 'TEXT' },
    json: { postgresql: 'JSONB', mysql: 'JSON', sqlite: 'TEXT' },
    uuid: { postgresql: 'UUID', mysql: 'VARCHAR(36)', sqlite: 'TEXT' },
  }
  return map[type]?.[dialect] ?? 'TEXT'
}

export function exportToSQL(schema: Schema, dialect: SQLDialect = 'postgresql'): string {
  const lines: string[] = [
    `-- Generated by beautyDB`,
    `-- Dialect: ${dialect}`,
    `-- Tables: ${schema.tables.length}`,
    '',
  ]

  // Sort tables by dependency order
  const sorted = topoSort(schema)

  for (const table of sorted) {
    lines.push(`CREATE TABLE "${table.name}" (`)

    const colLines: string[] = []
    const fkLines: string[] = []

    for (const col of table.columns) {
      const parts: string[] = []
      parts.push(`  "${col.name}"`)

      const isPK = col.modifiers.includes('primaryKey')
      const isAutoInc = col.modifiers.includes('autoincrement')

      if (isPK && isAutoInc) {
        if (dialect === 'postgresql') parts.push('SERIAL')
        else if (dialect === 'mysql') parts.push(`${mapTypeToSQL(col.type, dialect)} AUTO_INCREMENT`)
        else parts.push('INTEGER')
      } else {
        parts.push(mapTypeToSQL(col.type, dialect))
      }

      if (isPK) parts.push('PRIMARY KEY')
      if (col.modifiers.includes('required')) parts.push('NOT NULL')
      if (col.modifiers.includes('unique')) parts.push('UNIQUE')
      const defMod = col.modifiers.find((m) => m.startsWith('default:'))
      if (defMod) {
        const val = defMod.split(':')[1]
        parts.push(`DEFAULT ${val === 'now' ? 'CURRENT_TIMESTAMP' : `'${val}'`}`)
      }

      colLines.push(parts.join(' '))

      if (col.foreignKey) {
        fkLines.push(`  FOREIGN KEY ("${col.name}") REFERENCES "${col.foreignKey.table}" ("${col.foreignKey.column}")`)
      }
    }

    const allCols = [...colLines, ...fkLines]
    lines.push(allCols.join(',\n'))
    lines.push(');')
    lines.push('')
  }

  return lines.join('\n')
}

export function exportToBDL(schema: Schema): string {
  const lines: string[] = ['// Generated by beautyDB', '']

  for (const table of schema.tables) {
    lines.push(`table ${table.name} {`)
    for (const col of table.columns) {
      const parts: string[] = []
      if (col.modifiers.includes('primaryKey')) parts.push('*')
      parts.push(col.name)
      parts.push(col.type)
      if (col.foreignKey) parts.push(`-> ${col.foreignKey.table}`)
      const mods = col.modifiers.filter((m) => m !== 'primaryKey')
      if (mods.length) parts.push(mods.join(' '))
      lines.push(`  ${parts.join(' ')}`)
    }
    lines.push('}')
    lines.push('')
  }

  for (const link of schema.links) {
    lines.push(`link ${link.from.table} ${link.cardinality} ${link.to.table}`)
  }

  return lines.join('\n')
}

export function exportToPrisma(schema: Schema): string {
  const lines: string[] = ['// Generated by beautyDB\n// Prisma Schema\n']
  lines.push('generator client {\n  provider = "prisma-client-js"\n}\n')
  lines.push('datasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n')

  for (const table of schema.tables) {
    lines.push(`model ${table.name} {`)
    for (const col of table.columns) {
      const parts: string[] = [`  ${col.name}`]
      const prismaType = mapToPrismaType(col.type)
      parts.push(col.foreignKey ? 'Int' : prismaType)
      if (!col.modifiers.includes('required') && !col.modifiers.includes('primaryKey')) parts.push('?')
      if (col.modifiers.includes('primaryKey')) parts.push('@id')
      if (col.modifiers.includes('autoincrement')) parts[parts.length - 1] = '@id @default(autoincrement())'
      if (col.modifiers.includes('unique')) parts.push('@unique')
      lines.push(parts.join(' '))
    }
    lines.push('}')
    lines.push('')
  }
  return lines.join('\n')
}

function mapToPrismaType(t: ColType): string {
  const m: Record<ColType, string> = {
    int: 'Int', text: 'String', float: 'Float', date: 'DateTime',
    datetime: 'DateTime', bool: 'Boolean', image: 'String', json: 'Json', uuid: 'String',
  }
  return m[t] ?? 'String'
}

function topoSort(schema: Schema): Schema['tables'] {
  const tableMap = new Map(schema.tables.map((t) => [t.name, t]))
  const visited = new Set<string>()
  const result: Schema['tables'] = []

  const visit = (name: string, chain = new Set<string>()) => {
    if (visited.has(name)) return
    if (chain.has(name)) return // cycle
    chain.add(name)
    const table = tableMap.get(name)
    if (!table) return
    for (const col of table.columns) {
      if (col.foreignKey) visit(col.foreignKey.table, new Set(chain))
    }
    visited.add(name)
    result.push(table)
  }

  for (const table of schema.tables) visit(table.name)
  return result
}
