import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType, ImageRun, AlignmentType, BorderStyle } from 'docx'
import { Schema } from '@/lib/types/schema'

export async function generateDocxReport(schema: Schema, diagramImageBase64: string): Promise<Blob> {
  // Convert base64 to Buffer-like for docx (Uint8Array)
  const imageData = diagramImageBase64.split(',')[1]
  const binaryData = atob(imageData)
  const uint8Array = new Uint8Array(binaryData.length)
  for (let i = 0; i < binaryData.length; i++) {
    uint8Array[i] = binaryData.charCodeAt(i)
  }

  const sections = []

  // 1. Cover Page
  sections.push({
    properties: {},
    children: [
      new Paragraph({
        text: 'DATABASE DESIGN REPORT',
        heading: HeadingLevel.TITLE,
        alignment: AlignmentType.CENTER,
      }),
      new Paragraph({
        text: 'Generated by beautyDB AI',
        alignment: AlignmentType.CENTER,
      }),
      new Paragraph({ text: '' }),
      new Paragraph({
        children: [
          new ImageRun({
            data: uint8Array,
            transformation: {
              width: 600,
              height: 400,
            },
          }),
        ],
        alignment: AlignmentType.CENTER,
      }),
      new Paragraph({ text: '', pageBreakBefore: true }),
    ],
  })

  // 2. Table Definitions
  const tableContent: any[] = [
    new Paragraph({
      text: 'Detailed Table Specifications',
      heading: HeadingLevel.HEADING_1,
    }),
  ]

  schema.tables.forEach((table) => {
    tableContent.push(
      new Paragraph({
        text: `Table: ${table.name}`,
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 400 },
      })
    )

    if (table.note) {
      tableContent.push(
        new Paragraph({
          children: [
            new TextRun({ text: 'Description: ', bold: true }),
            new TextRun({ text: table.note, italics: true }),
          ],
        })
      )
    }

    // Columns Table
    const rows = [
      new TableRow({
        children: [
          new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Field', bold: true })] })], width: { size: 25, type: WidthType.PERCENTAGE } }),
          new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Type', bold: true })] })], width: { size: 20, type: WidthType.PERCENTAGE } }),
          new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Constraints', bold: true })] })], width: { size: 25, type: WidthType.PERCENTAGE } }),
          new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Note', bold: true })] })], width: { size: 30, type: WidthType.PERCENTAGE } }),
        ],
      }),
    ]

    table.columns.forEach((col) => {
      const constraints = []
      if (col.modifiers.includes('primaryKey')) constraints.push('PK')
      if (col.foreignKey) constraints.push(`FK (${col.foreignKey.table})`)
      if (col.modifiers.includes('unique')) constraints.push('Unique')
      if (col.modifiers.includes('required')) constraints.push('Not Null')

      rows.push(
        new TableRow({
          children: [
            new TableCell({ children: [new Paragraph(col.name)] }),
            new TableCell({ children: [new Paragraph(col.type)] }),
            new TableCell({ children: [new Paragraph(constraints.join(', '))] }),
            new TableCell({ children: [new Paragraph(col.note || '')] }),
          ],
        })
      )
    })

    tableContent.push(
      new Table({
        rows,
        width: { size: 100, type: WidthType.PERCENTAGE },
      })
    )
  })

  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [...sections[0].children, ...tableContent],
      },
    ],
  })

  const buffer = await Packer.toBlob(doc)
  return buffer
}
